CREATE TABLE PUBLIC.TB_PESSOA (
        CODIGO UUID NOT NULL,
        CATEGORIA VARCHAR(255) NOT NULL,
        NOME VARCHAR(255) NOT NULL,
        PRIMARY KEY (CODIGO)
);
ALTER TABLE IF EXISTS PUBLIC.TB_PESSOA
       ADD CONSTRAINT UK_GI38CV4U55BYAT7G2XKB60BDR UNIQUE (NOME);
