CREATE TABLE PUBLIC.TB_COFRE (
        CODIGO BIGSERIAL NOT NULL,
        CATEGORIA VARCHAR(255) NOT NULL,
        CHAVE VARCHAR(255) NOT NULL,
        DATA_ATUALIZACAO TIMESTAMP(6) NOT NULL,
        DATA_CADASTRO TIMESTAMP(6) NOT NULL,
        DATA_VENCIMENTO TIMESTAMP(6) NOT NULL,
        IDENTIFICADOR VARCHAR(255) NOT NULL,
        TITULO VARCHAR(255) NOT NULL,
        ID_PESSOA_GERENCIADA UUID NOT NULL,
        ID_PESSOA_RESPONSAVEL UUID NOT NULL,
        PRIMARY KEY (CODIGO)
);

ALTER TABLE IF EXISTS PUBLIC.TB_COFRE
       ADD CONSTRAINT UK_T3VHVL5PLWJ0YPB6F13NMWGIY UNIQUE (TITULO);

ALTER TABLE IF EXISTS PUBLIC.TB_COFRE
       ADD CONSTRAINT FKSQSIV1G1AUVPBQDX7DC453AQP
       FOREIGN KEY (ID_PESSOA_GERENCIADA)
       REFERENCES PUBLIC.TB_PESSOA;

ALTER TABLE IF EXISTS PUBLIC.TB_COFRE
       ADD CONSTRAINT FK27YT80PE8X39G2DHT60TS68JT
       FOREIGN KEY (ID_PESSOA_RESPONSAVEL)
       REFERENCES PUBLIC.TB_PESSOA;